add app_version

diff --git a/.github/workflows/test-version-build-push.yml b/.github/workflows/test-version-build-push.yml
--- a/.github/workflows/test-version-build-push.yml
+++ b/.github/workflows/test-version-build-push.yml
@@ -11,6 +11,7 @@ on:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
+  VERSION:
   PLATFORMS:
   LOCAL:
 
@@ -57,32 +58,41 @@ jobs:
     needs: test
     runs-on: ubuntu-latest
     outputs:
-      tagged_version: ${{ steps.current_tag.outputs.tag }}
+      app_version: ${{ steps.current_tag.outputs.app_version }}
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4   
         
-      - name: Get the current tag
+      - name: Get the current tag/branch
         id: current_tag
         run: |
-          # Extrahiere den aktuellen Tag (z.B. v1.2.0)
-          CURRENT_TAG=${GITHUB_REF#refs/tags/}
-          echo "Current tag: $CURRENT_TAG"
-          
-          # Überprüfe, ob der Tag dem Schema v0.0.0[-suffix] entspricht
-          if [[ ! "$CURRENT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
-            echo "Error: The tag $CURRENT_TAG does not match the required schema v0.0.0[-suffix]."
-            exit 1
-          fi
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
 
-          # Speichere den Tag in GITHUB_OUTPUT
-          echo "tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
+            # Extrahiere den aktuellen Tag (z.B. v1.2.0)
+            CURRENT_TAG=${GITHUB_REF#refs/tags/}
+            echo "Current tag: $CURRENT_TAG"
+            
+            # Überprüfe, ob der Tag dem Schema v0.0.0[-suffix] entspricht
+            if [[ ! "$CURRENT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
+              echo "Error: The tag $CURRENT_TAG does not match the required schema v0.0.0[-suffix]."
+              exit 1
+            fi
+
+            # Speichere den Tag in GITHUB_OUTPUT
+            echo "app_version=$CURRENT_TAG" >> $GITHUB_OUTPUT
+          else
+            VERSION="${GITHUB_REF#refs/heads/}"
+            VERSION="${VERSION//\//-}"
+
+            echo "app_version=$VERSION" >> $GITHUB_OUTPUT
+          fi
 
       - name: Get the previous tag
         id: previous_tag
+        if: startsWith(github.ref, 'refs/tags/')       # <-- läuft nur bei Tags
         run: |
           # Hol dir den CURRENT_TAG aus dem vorherigen Schritt
-          CURRENT_TAG="${{ steps.current_tag.outputs.tag }}"
+          CURRENT_TAG="${{ steps.current_tag.outputs.app_version }}"
           
           # Finde alle Tags und sortiere sie nach Erstellungsdatum
           # Ignoriere den aktuellen Tag
@@ -98,8 +108,9 @@ jobs:
 
       - name: Compare tags
         id: compare
+        if: startsWith(github.ref, 'refs/tags/')       # <-- läuft nur bei Tags
         run: |
-          CURRENT_TAG="${{ steps.current_tag.outputs.tag }}"
+          CURRENT_TAG="${{ steps.current_tag.outputs.app_version }}"
           PREVIOUS_TAG="${{ steps.previous_tag.outputs.previous_tag }}"
 
           # Entferne das "v" vor den Versionsnummern
@@ -119,16 +130,19 @@ jobs:
             exit 1
           fi
 
+    
       - name: Update Version in influxdb-to-file.sh
         run: |
-          CURRENT_TAG="${{ steps.current_tag.outputs.tag}}"
+          CURRENT_TAG="${{ steps.current_tag.outputs.app_version}}"
           PREVIOUS_TAG="${{ steps.previous_tag.outputs.previous_tag }}"
 
           CURRENT_TAG="${CURRENT_TAG#v}"  # entfernt führendes 'v', falls vorhanden
           PREVIOUS_TAG="${PREVIOUS_TAG#v}"  # optional für vorherigen Tag
 
-          echo "Updating influxdb-to-file.sh with tag $CURRENT_TAG"
+          echo "Updating influxdb-to-file.sh with tag/branch $CURRENT_TAG"
           sed -i "s/^readonly VERSION=.*/readonly VERSION=\"$CURRENT_TAG\"/" influxdb-to-file.sh
+
+          exit 0
           
       - name: Upload bumped influxdb-to-file.sh
         uses: actions/Upload-artifact@v4
@@ -178,6 +192,14 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
      
+      - name: Strip leading v from app_version
+        id: strip_v
+        run: |
+          VERSION="${{ needs.bump-version.outputs.app_version }}"
+          VERSION="${VERSION#v}"
+          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
+          echo "stripped_version=$VERSION" >> $GITHUB_OUTPUT
+
 
       - name: Build Docker Image
         uses: docker/build-push-action@v6
@@ -187,7 +209,7 @@ jobs:
           push: ${{ env.LOCAL != 'true' }}
           load: ${{ env.LOCAL == 'true' }}
           tags: |
-            ghcr.io/${{ github.repository }}:${{ needs.bump-version.outputs.tagged_version }}
+            ghcr.io/${{ github.repository }}:${{ steps.strip_v.outputs.stripped_version }}
             ${{ github.ref_type == 'tag' && format('ghcr.io/{0}:latest', github.repository) || '' }}
            
         
